<?php

declare(strict_types=1);

namespace AxonPHP\Cli\Provider;

use AxonPHP\Cli\Project\Project;
use AxonPHP\Cli\Project\Tool;
use AxonPHP\Cli\Project\ToolType;

/**
 * The few YAML primitives and shell snippets the providers share.
 */
final class Yaml
{
    public const HEADER = '# Generated by AxonPHP CLI (https://github.com/maximilianfeix/AxonPHPCLI). Edit freely.';

    public const LINT_COMMAND = "find . -type f -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l";

    public const INSTALL_COMMAND = 'composer install --prefer-dist --no-progress';

    public const LOWEST_COMMAND = 'composer update --prefer-lowest --prefer-stable --prefer-dist --no-progress';

    public const AUDIT_COMMAND = 'composer audit';

    private const EXTENSION_INSTALLER = 'https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions';

    /**
     * The commands of the project's test tools, or a syntax check when it has none.
     *
     * @return list<string>
     */
    public static function testCommands(Project $project): array
    {
        $tools = $project->tools(ToolType::Tests);

        if ([] === $tools) {
            return [self::LINT_COMMAND];
        }

        return array_map(static fn (Tool $tool): string => $tool->command, $tools);
    }

    public static function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }

    /**
     * @param list<string> $values
     */
    public static function inlineList(array $values): string
    {
        return '['.implode(', ', array_map(self::quote(...), $values)).']';
    }

    /**
     * Shell commands that add Composer and the given extensions to an official "php" Docker image.
     *
     * @param list<string> $extensions
     *
     * @return list<string>
     */
    public static function dockerSetup(array $extensions): array
    {
        return [
            'curl -sSLf -o /usr/local/bin/install-php-extensions '.self::EXTENSION_INSTALLER,
            'chmod +x /usr/local/bin/install-php-extensions',
            'install-php-extensions '.implode(' ', ['@composer', 'zip', ...$extensions]),
        ];
    }
}
