<?php

declare(strict_types=1);

namespace AxonPHP\Cli\Provider;

/**
 * The few YAML primitives the providers need to emit safe scalars.
 */
final class Yaml
{
    public const HEADER = '# Generated by AxonPHP CLI (https://github.com/0d6v/AxonPHPCLI). Edit freely.';

    public const LINT_COMMAND = "find . -type f -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l";

    public static function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }

    /**
     * @param list<string> $values
     */
    public static function inlineList(array $values): string
    {
        return '['.implode(', ', array_map(self::quote(...), $values)).']';
    }
}
