<?php

declare(strict_types=1);

namespace AxonPHP\Cli\Provider;

/**
 * The few YAML primitives and shell snippets the providers share.
 */
final class Yaml
{
    public const HEADER = '# Generated by AxonPHP CLI (https://github.com/maximilianfeix/AxonPHPCLI). Edit freely.';

    /** Adds the coverage driver to an official "php" Docker image that went through dockerSetup(). */
    public const PCOV_COMMAND = 'install-php-extensions pcov';

    private const EXTENSION_INSTALLER = 'https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions';

    public static function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }

    /**
     * @param list<string> $values
     */
    public static function inlineList(array $values): string
    {
        return '['.implode(', ', array_map(self::quote(...), $values)).']';
    }

    /**
     * Shell commands that add Composer and the given extensions to an official "php" Docker image.
     *
     * @param list<string> $extensions
     *
     * @return list<string>
     */
    public static function dockerSetup(array $extensions): array
    {
        return [
            'curl -sSLf -o /usr/local/bin/install-php-extensions '.self::EXTENSION_INSTALLER,
            'chmod +x /usr/local/bin/install-php-extensions',
            'install-php-extensions '.implode(' ', ['@composer', 'zip', ...$extensions]),
        ];
    }
}
